[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
tally_clob = "B98rqLdQhCMUzRZiE8DSp55bx8JEfJbuUkw1Ln3fMrKQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
