[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
tally_clob = "CPtwPtwjQhPbfZYsHiWskky7gRtBcRzFsh4HvsQ5tmXe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./mvp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
